2018-03-24 09:57:17,225 data_sync_assisant.py[line: 139] WARNING: 没找到测试步骤操作的用例对象id
2018-03-24 10:00:39,244 data_sync_assisant.py[line: 130] ERROR: 正在同步测试步骤表中用例(ID：93)所在页面信息及用例名称成功
2018-03-24 10:03:30,699 data_sync_assisant.py[line: 148] WARNING: ---------------------------start----------------------------------
2018-03-24 10:03:30,824 data_sync_assisant.py[line: 151] WARNING: ---------------------------end----------------------------------



